const authMap = {
  // 用户管理-查看
  new_AUTH_userManage_View: 59,
  // 用户管理-新建
  new_AUTH_userManage_Edit: 60,
  // 用户管理-编辑
  new_AUTH_userManage_Create: 61,
  // 权限组管理-查看
  new_AUTH_authGroupManage_View: 62,
  // 权限组管理-新建
  new_AUTH_authGroupManage_Create: 63,
  // 权限组管理-编辑
  new_AUTH_authGroupManage_Edit: 131,
  // 权限管理-查看
  new_AUTH_authManage_View: 64,
  // 权限管理-新建
  new_AUTH_authManage_Create: 65,
  // 权限管理-编辑
  new_AUTH_authManage_Edit: 66,
  // 班次管理-收派仓管理-查看
  new_AUTH_storeBatchManagement_View: 67,
  // 网格管理-查看
  new_AUTH_aoiManagement_View: 68,
  // 临近AOI-查看
  new_AUTH_adjacentAoi_View: 69,
  // 收派员信息-查看
  new_AUTH_courierInfo_View: 70,
  // 收派员信息-导出
  new_AUTH_courierInfo_Export: 71,
  // 收派员信息-编辑格口
  new_AUTH_courierInfo_Edit: 72,
  // 月度轮休-查看
  new_AUTH_courierOrder_View: 73,
  // 月度轮休-初始化轮休方案
  new_AUTH_courierOrder_Initial: 74,
  // 月度轮休-发起替班
  new_AUTH_courierOrder_Replace: 75,
  // 月度轮休-高峰期取消轮休
  new_AUTH_courierOrder_Cancel: 76,
  // 月度轮休-导出
  new_AUTH_courierOrder_Export: 77,
  // 替班记录管理-查看
  new_AUTH_SubstituteManage_View: 78,
  // 替班记录管理-导出
  new_AUTH_SubstituteManage_Export: 79,
  // 替班记录管理-撤销
  new_AUTH_SubstituteManage_Cancel: 80,
  // AOI调度-查看
  new_AUTH_areaDistributeManage_View: 81,
  // 改派记录-查看
  new_AUTH_reassignRecord_View: 82,
  // 改派记录-导出
  new_AUTH_reassignRecord_Export: 83,
  // AOI调度-改派
  new_AUTH_areaDistributeManage_Redispatch: 84,
  // AOI调度-导出
  new_AUTH_areaDistributeManage_Export: 85,
  // 派件数据-查看
  // 收件明细报表-查看
  // 收派件执行导出-导出
  new_AUTH_receiveDispatchData_ViewAndExport: 86,
  // 区域数据图表-查看
  new_AUTH_tcDataChart_View: 87,
  // 区域数据详情图表-查看
  new_AUTH_tcDataChartDetail_View: 88,
  // 区域数据图表-导出
  new_AUTH_tcDataChart_Exoprt: 89,
  // AOI组配置-AOI组管理-查看-delete
  new_AUTH_aoiGroupManage_View: 90,
  // AOI组配置-统计数据-查看-delete
  new_AUTH_aoiGroupManageStatistics_View: 91,
  // AOI组配置-AOI组管理-新建-delete
  new_AUTH_aoiGroupManage_Create: 92,
  // AOI组配置-AOI组管理-编辑-delete
  new_AUTH_aoiGroupManage_Edit: 93,
  // AOI组配置-AOI组管理-废弃-delete
  new_AUTH_aoiGroupManage_Discard: 94,
  // AOI组配置-AOI组管理-更新排班
  new_AUTH_aoiGroupManage_Update: 95,
  // AOI组配置-统计数据-导出-delete
  new_AUTH_aoiGroupManageStatistics_Export: 96,
  // 排班任务-查看
  new_AUTH_scheduleTask_View: 97,
  // 排班任务-创建排班任务
  new_AUTH_scheduleTask_Create: 98,
  // 排班任务-排班应用
  new_AUTH_scheduleTask_Apply: 99,
  // 规则管理-查看
  new_AUTH_regionRuleManage_View: 100,
  // 规则管理-新建
  new_AUTH_regionRuleManage_Create: 101,
  // 规则管理-编辑
  new_AUTH_regionRuleManage_Edit: 102,
  // 规则管理-删除
  new_AUTH_regionRuleManage_Delete: 103,
  // 规则管理-任务分发
  new_AUTH_regionRuleManage_Dispatch: 104,
  // 区域直管任务-查看
  new_AUTH_regionTaskManage_View: 105,
  // 区域直管任务-详情页查看
  new_AUTH_regionTaskDetail_View: 106,
  // 区域直管任务-详情页导出
  new_AUTH_regionTaskDetail_Export: 107,
  // 区域直管任务-处理任务系列操作
  new_AUTH_regionTaskDetail_Operate: 108,
  // 区域直管任务-区域审批
  new_AUTH_regionTaskDetail_RegionalApproval: 109,
  // 区域直管任务-导出列表
  new_AUTH_RegionTaskManage_ExportList: 110,
  // 区域直管任务-导出详情
  new_AUTH_RegionTaskManage_ExportDetail: 111,
  // 通知人管理-查看
  new_AUTH_alarmManage_View: 112,
  // 通知人管理-新增
  new_AUTH_alarmManage_Create: 113,
  // 通知人管理-编辑-delete
  new_AUTH_alarmManage_Edit: 114,
  // 末班次合并-查看
  new_AUTH_tcLastBatchMerge_View: 115,
  // 排班应用监控-查看
  new_AUTH_tcMonitor_View: 116,
  // 排班应用监控-导出
  new_AUTH_tcMonitor_Export: 117,
  // 末班次合并-编辑单元区域
  new_AUTH_TcLastBatchMerge_Edit: 132,
  // 末班次合并-调整上班日期
  new_AUTH_TcLastBatchMerge_Update: 118,
  // 末班次合并-恢复默认排班
  new_AUTH_TcLastBatchMerge_Reset: 119,
  // 末班次合并-确定排班结果
  new_AUTH_TcLastBatchMerge_Confirm: 120,
  // 热力图-查看
  new_AUTH_HeatMap_View: 121,
  // 热力图-导出
  new_AUTH_HeatMap_Export: 122,
  // 智排班审批权限-查看
  new_AUTH_aiCheckManage_View: 123,
  // 智排班审批权限-新增
  new_AUTH_aiCheckManage_Create: 124,
  // 智排班审批权限-编辑-delete
  new_AUTH_aiCheckManage_Edit: 125,
  // 高峰预警-查看
  new_AUTH_PeakWarning_View: 126,
  // 高峰预警-全职派件量效能修改
  new_AUTH_PeakWarning_Edit: 127,
  // 高峰预警-导出
  new_AUTH_PeakWarning_Export: 128,
  // 小哥上报平台-查看
  new_AUTH_courierReport_View: 129,
  // 小哥上报平台-导出
  new_AUTH_courierReport_Export: 130,
  // TC变更台账-查看
  new_AUTH_RegionAdjustStandingBook_View: 133,
  // TC变更台账-导出
  new_AUTH_RegionAdjustStandingBook_Export: 134,
  // AOI数据表-查看
  new_AUTH_aoiDatabase_View: 135,
  // AOI数据表-导出
  new_AUTH_aoiDatabase_Export: 136,
  //网点管理-查看
  new_AUTH_outLets_view: 142,
  //网点管理-开通-查看审核
  new_AUTH_outLets_open: 143,
  //网点管理-批量
  new_AUTH_outLets_batch: 144,
  // 消息管理-查看/设置已读
  new_AUTH_messageManage_ViewAndSet: 145,
  // 审批管理-查看/查询
  new_AUTH_approvalManage_ViewAndSearch: 146,
  // 审批管理-审批处理
  new_AUTH_approvalManage_Approval: 147,
  // 数据运营-其他数据导出-扫码寄件-查看
  new_AUTH_scanAndSend_View: 148,
  // 数据运营-其他数据导出-扫码寄件-查看
  new_AUTH_aoiDataView_View: 229,
  // 数据运营-其他数据导出-运单打印异常报表-查看
  new_AUTH_printErrorView_View: 234,
  // 数据运营-其他数据导出-人员高效能预警明细-查看
  new_AUTH_HignEfficiency_View: 249,
  // 数据运营-其他数据导出-分配单元吻合率导出
  new_AUTH_ExecutionDetailUnit_View: 255,
  // 数据运营-其他数据导出-错分件-查看
  new_AUTH_errorPartsView_View: 233,
  // AOI区域配置-查看
  new_AUTH_AoiAreaManage_View: 149,
  // AOI区域配置-编辑
  new_AUTH_AoiAreaManage_Edit: 150,
  // AOI区域配置-数据统计导出
  new_AUTH_AoiAreaManage_DataExport: 151,
  // AOI区域配置-废弃-delete
  new_AUTH_AoiAreaManage_Discard: 152,
  // AOI区域配置-更新排班
  new_AUTH_AoiAreaManage_UpdateSchedule: 153,
  // AOI区域配置-新建
  new_AUTH_AoiAreaManage_Create: 154,
  // AOI区域配置-区域图层配置
  new_AUTH_AoiAreaManage_Layers: 196,
  // AOI区域配置-数据统计查看
  new_AUTH_AoiAreaManage_DataLook: 155,
  // 区域直管任务-总部审批
  new_AUTH_regionTaskDetail_HeadquartersApproval: 156,
  // aoi区域配置-区域图层配置-新建、编辑、批量导入
  new_AUTH_AreaLayerConfig_Edit: 157,
  // aoi区域配置-区域图层配置-查看、导出
  new_AUTH_AreaLayerConfig_Look: 158,
  // aoi区域配置-AOI区域编码-编辑
  new_AUTH_AreaLayerConfig_AoiAreaId_Edit: 181,
  // aoi区域配置-AOI区域类型-编辑-delete
  new_AUTH_AreaLayerConfig_AoiAreaType_Edit: 182,
  // AOI区域配置-AOI组管理-新建
  new_AUTH_aoiAreaGroupManage_Create: 159,
  // AOI区域配置-AOI组管理-编辑
  new_AUTH_aoiAreaGroupManage_Edit: 160,
  // AOI区域配置-AOI组管理-查看
  new_AUTH_aoiAreaGroupManage_view: 161,
  // AOI区域配置-AOI组管理-废弃
  new_AUTH_aoiAreaGroupManage_Discard: 162,
  // AOI区域配置-AOI组管理-更新排班-delete
  new_AUTH_aoiAreaGroupManage_UpdateSchedule: 163,
  // 排班任务-查看
  new_AUTH_ScheduleTask_Look: 164,
  // 规则管理-新建规则-测试
  new_AUTH_RegionRuleCreate_IsTest: 165,
  // 月度轮休（新）-一键排班
  new_AUTH_newCourierOrder_Schedule: 171,
  // 月度轮休（新）-导入替班
  new_AUTH_newCourierOrder_export: 172,
  // 轮休组管理 -- 查看
  new_AUTH_RotationRestGroup_View: 166,
  // 轮休组管理 -- 新建
  new_AUTH_RotationRestGroup_New: 167,
  // 轮休组管理 -- 编辑
  new_AUTH_RotationRestGroup_Edit: 168,
  // 轮休组管理 -- 删除
  new_AUTH_RotationRestGroup_Del: 169,
  // 通用配班-查看
  new_AUTH_GeneralArrangement_View: 170,
  // 通用配班-导入
  new_AUTH_GeneralArrangement_Import: 173,
  // 通用配班-导出
  new_AUTH_GeneralArrangement_Export: 174,
  // 通用配班-编辑
  new_AUTH_GeneralArrangement_Edit: 175,
  // 通用配班-删除
  new_AUTH_GeneralArrangement_Delete: 178,
  // 通用配班-详情
  new_AUTH_GeneralArrangement_Detail: 179,
  // 收派件管理-查看
  new_AUTH_PackageBatchManagement_View: 176,
  // 收派件管理-导出
  new_AUTH_PackageBatchManagement_Export: 177,
  // 月度轮休（新 旧）-意愿休息下发
  new_AUTH_courierOrder_wishrest: 183,
  // aoi区域配置-小组模式抢单开关
  new_AUTH_aoiArea_grab: 184,
  // 工作台-四象限-查看
  new_AUTH_FourQuadrant_View: 250,
  // 收派吻合导出-查看
  new_AUTH_receiveDispatchExport_View: 185,
  // 收派吻合导出-导出
  new_AUTH_receiveDispatchExport_Export: 186,
  // AOI区域配置-AOI组配置-新建/编辑-是否动态分配
  new_AUTH_aoiAreaManage_isDynamic: 187,
  // 数据运营-其他数据导出-意愿休息-查看-delete
  new_AUTH_willRest_View: 188,
  // aoi区域数据库-查看
  new_AUTH_aoiAreaDatabase_View: 189,
  // aoi区域数据库-导出
  new_AUTH_aoiAreaDatabase_Export: 190,
  // AOI区域变更记录-查看（页面+按钮）/编辑
  new_AUTH_aoiAreaChangeRecord_ViewAndEdit: 191,
  // AOI区域变更记录-导出
  new_AUTH_aoiAreaChangeRecord_Export: 192,
  // AOI区域变更记录-审核
  new_AUTH_aoiAreaChangeRecord_Approval: 193,
  // AOI区域变更记录-日志
  new_AUTH_aoiAreaChangeRecord_logger: 194,
  // AOI区域变更记录-撤销
  new_AUTH_aoiAreaChangeRecord_revoke: 195,
  // 收派件班次-新建/编辑
  new_AUTH_PackageBatchManagement_change: 197,
  // 收派件班次-查看
  new_AUTH_PackageBatchManagement_view: 198,
  // 收派件班次-删除
  new_AUTH_PackageBatchManagement_delete: 199,
  // 拆分补贴申请-查看
  new_AUTH_SplitSubsidyApply_View: 200,
  // 拆分补贴申请-新建/编辑
  new_AUTH_SplitSubsidyApply_CreateAndEdit: 201,
  // 拆分补贴申请-导出
  new_AUTH_SplitSubsidyApply_Export: 202,
  // 拆分补贴申请-审批
  new_AUTH_SplitSubsidyApply_Approval: 203,
  // 拆分补贴申请-撤回
  new_AUTH_SplitSubsidyApply_Revoke: 204,
  // 拆分补贴申请-日志
  new_AUTH_SplitSubsidyApply_Logger: 205,
  // 拆分补贴结算-查看
  new_AUTH_SplitSubsidySettlement_view: 206,
  // 拆分补贴结算-审批
  new_AUTH_SplitSubsidySettlement_approve: 207,
  // 拆分补贴结算-日志
  new_AUTH_SplitSubsidySettlement_log: 208,
  // 拆分补贴结算-导出
  new_AUTH_SplitSubsidySettlement_export: 209,
  // 意愿休息开关
  new_AUTH_WishRest_switch: 210,
  // AOI区域规则管理-新建
  new_AUTH_aoiAreaRegionRuleManage_Create: 211,
  // AOI区域规则管理-查看
  new_AUTH_aoiAreaRegionRuleManage_View: 212,
  // AOI区域规则管理-编辑
  new_AUTH_aoiAreaRegionRuleManage_Edit: 213,
  // AOI区域规则管理-删除
  new_AUTH_aoiAreaRegionRuleManage_Delete: 214,
  // AOI区域规则管理-新建规则-测试
  new_AUTH_aoiAreaRegionRuleCreate_IsTest: 223,
  // AOI区域直管任务-查看
  new_AUTH_newRegionTask_view: 215,
  // AOI区域直管任务-详情页查看
  new_AUTH_newRegionTask_detailView: 216,
  // AOI区域直管任务-处理任务系列操作
  new_AUTH_newRegionTask_dealTask: 217,
  // AOI区域直管任务-地区审核
  new_AUTH_newRegionTask_areaApprove: 218,
  // AOI区域直管任务-总部审核
  new_AUTH_newRegionTask_headApprove: 219,
  // AOI区域直管任务-导出列表
  new_AUTH_newRegionTask_exportList: 220,
  // AOI区域直管任务-导出详情
  new_AUTH_newRegionTask_exportDetail: 221,
  // AOI区域直管任务-详情页导出
  new_AUTH_newRegionTask_detailPageExport: 222,
  // 分配单元配置-查看
  new_AUTH_AllocationUnit_View: 226,
  // 分配单元配置-新建/编辑
  new_AUTH_AllocationUnit_CreateAndEdit: 227,
  // 分配单元配置-日志
  new_AUTH_AllocationUnit_Logger: 228,
  // 分配单元配置情况导出
  new_AUTH_DistributionUnit_Export: 230,
  // 运营小工具
  new_AUTH_OperationTool_View: 224,
  // 标签配置
  new_AUTH_LabelConfig_View: 236,
  //标签对比工具
  new_AUTH_TagCompareTool_View: 246,
  new_AUTH_LabelConfig_Import: 237,
  new_AUTH_LabelConfig_Edit: 238,
  // 收派员信息-编辑员工类型
  new_AUTH_courierInfo_EditMotorType: 231,
  // 收派员信息-员工类型批量上传
  new_AUTH_courierInfo_BatchUploadMotorType: 232,
  // AOI区域变更列表重货状态
  new_AUTH_aoiAreaManage_zh_status: 240,
  // 意愿休息数据看板-查看
  new_AUTH_RestPanel_View: 235,
  // 路径规划-查看
  new_AUTH_routePlane_View: 239,
  // 高峰预警-提交高峰期人员排布数据
  new_AUTH_PeakWarning_Arrangement_Data_Submit: 241,
  // 高峰预警-临时派件量效能修改
  new_AUTH_PeakWarningTmpBenchmark_Modify: 242,
  // 高峰预警-预计派件量修改
  new_AUTH_PeakWarningPresend_Modify: 243,
  // 高峰预警-数据提交记录-查看
  new_AUTH_PeakWarningDataSubmitRecord_View: 244,
  // 高峰预警-数据提交记录-导出
  new_AUTH_PeakWarningDataSubmitRecord_Export: 245,
  // 国际件专收配班-查看
  new_AUTH_InternationalExpress_View: 251,
  // 国际件专收配班-新建和编辑
  new_AUTH_InternationalExpress_Edit: 252,
  // 国际件专收配班-删除
  new_AUTH_InternationalExpress_Delete: 253,
  // 国际件专收配班-导出
  new_AUTH_InternationalExpress_Export: 254,
  // AOI区域变更审核记录-跨网点调整-推迟生效时间
  new_AUTH_aoiAreaChangeRecord_Delay_EffectiveTime: 256,
  // AOI区域变更-跨网点
  new_AUTH_AoiAreaManage_cross: 257,
  // 高峰预警-临时加人
  new_AUTH_PeakWarning_addCourier: 258,
  // 订单管理-查看
  new_AUTH_OrderManage_view: 266,
  // 订单管理-电话解密
  new_AUTH_OrderManage_Decrypt_tel: 267,
  // 订单管理-地址解密
  new_AUTH_OrderManage_Decrypt_addr: 268,
  // AOI区域规则管理-低收配置-查看
  new_AUTH_aoiAreaRegionLowIncomeConfig_View: 260,
  // AOI区域规则管理-低收配置-导入
  new_AUTH_aoiAreaRegionLowIncomeConfig_Import: 261,
  // AOI区域规则管理-低收配置-导出
  new_AUTH_aoiAreaRegionLowIncomeConfig_Export: 262,
  // 直管任务预测工具-查看
  new_AUTH_RegionTaskPredictionTool_View: 264,
  // 直管任务预测工具-新建预测/查看单条预测
  new_AUTH_RegionTaskPredictionTool_Create: 265,
  // AOI区域直管任务-撤销任务
  new_AUTH_newRegionTask_revokeTask: 263,

  // 2.旧权限编码

  // 用户管理_查看-delete
  old_AUTH_userManage_View: 1,
  // 用户管理-修改-delete
  old_AUTH_userManage_Edit: 2,
  old_AUTH_userManage_Create: 2,
  // 权限组管理-查看-delete
  old_AUTH_authGroupManage_View: 3,
  // 权限组管理-修改-delete
  old_AUTH_authGroupManage_Create: 4,
  old_AUTH_authGroupManage_Edit: 4,
  // 权限管理-查看-delete
  old_AUTH_authManage_View: 5,
  // 权限管理-修改-delete
  old_AUTH_authManage_Create: 6,
  old_AUTH_authManage_Edit: 6,
  // 班次管理-查看-delete
  old_AUTH_batchManagement_View: 7,
  // 网格管理-查看-delete
  old_AUTH_aoiManagement_View: 8,
  old_AUTH_adjacentAoi_View: 8,
  // 收派员管理-查看-delete
  old_AUTH_courierInfo_View: 10,
  // 收派员信息-操作-delete
  old_AUTH_courierInfo_Export: 11,
  old_AUTH_courierInfo_Edit: 11,
  // 月度轮休-查看-delete
  old_AUTH_courierOrder_View: 12,
  // 月度轮休-操作-delete
  old_AUTH_courierOrder_Initial: 13,
  old_AUTH_courierOrder_Replace: 13,
  old_AUTH_courierOrder_Cancel: 13,
  old_AUTH_courierOrder_Export: 13,
  // 替班记录管理-查看-delete
  old_AUTH_SubstituteManage_View: 14,
  // 替班记录管理-操作-delete
  old_AUTH_SubstituteManage_Export: 15,
  old_AUTH_SubstituteManage_Cancel: 15,
  // 区域管理-查看-delete
  old_AUTH_areaDistributeManage_View: 16,
  old_AUTH_reassignRecord_View: 16,
  old_AUTH_reassignRecord_Export: 16,
  // 区域管理-操作-delete
  old_AUTH_areaDistributeManage_Redispatch: 17,
  old_AUTH_areaDistributeManage_Export: 17,
  // 派件数据-查看
  // 收件明细报表-查看-delete
  old_AUTH_receiveDispatchData_ViewAndExport: 20,
  // 区域数据图表-查看-delete
  old_AUTH_tcDataChart_View: 25,
  // 区域数据详情图表-查看-delete
  old_AUTH_tcDataChartDetail_View: 25,
  // 区域直管指标导出-delete
  old_AUTH_tcDataChart_Exoprt: 26,
  // AOI组信息查看-delete
  old_AUTH_aoiGroupManage_View: 27,
  old_AUTH_aoiGroupManageStatistics_View: 27,
  old_AUTH_aoiGroupManageStatistics_Export: 27,
  // AOI组信息新增、修改-delete
  old_AUTH_aoiGroupManage_Create: 28,
  old_AUTH_aoiGroupManage_Edit: 28,
  old_AUTH_aoiGroupManage_Discard: 28,
  old_AUTH_aoiGroupManage_Update: 28,
  // 排班任务查看-delete
  old_AUTH_scheduleTask_View: 29,
  // 排班任务操作-delete
  old_AUTH_scheduleTask_Create: 30,
  old_AUTH_scheduleTask_Apply: 30,
  // 规则管理-查看和编辑-delete
  old_AUTH_regionRuleManage_View: 33,
  old_AUTH_regionRuleManage_Create: 33,
  old_AUTH_regionRuleManage_Edit: 33,
  old_AUTH_regionRuleManage_Delete: 33,
  old_AUTH_regionRuleManage_Dispatch: 33,
  // 任务看板-查看-delete
  old_AUTH_regionTaskManage_View: 34,
  old_AUTH_regionTaskDetail_View: 34,
  old_AUTH_regionTaskDetail_Export: 34,
  old_AUTH_regionTaskDetail_Operate: 34,
  old_AUTH_regionTaskDetail_Approval: 34,
  // 区域直管任务-导出列表-delete
  old_AUTH_RegionTaskManage_ExportList: 54,
  // 区域直管任务-导出详情-delete
  old_AUTH_RegionTaskManage_ExportDetail: 55,
  // 异常通知管理-delete
  old_AUTH_alarmManage_View: 35,
  old_AUTH_alarmManage_Create: 35,
  old_AUTH_alarmManage_Edit: 35,
  // 末班次合并查看-delete
  old_AUTH_tcLastBatchMerge_View: 38,
  old_AUTH_tcMonitor_View: 38,
  old_AUTH_tcMonitor_Export: 38,
  // 末班次合并操作-delete
  old_AUTH_TcLastBatchMerge_Edit: 39,
  old_AUTH_TcLastBatchMerge_Update: 39,
  old_AUTH_TcLastBatchMerge_Reset: 39,
  old_AUTH_TcLastBatchMerge_Confirm: 39,
  // 热力图-查看-delete
  old_AUTH_HeatMap_View: 41,
  // 热力图_导出-delete
  old_AUTH_HeatMap_Export: 43,
  // 替班审批-delete
  old_AUTH_aiCheckManage_View: 42,
  old_AUTH_aiCheckManage_Create: 42,
  old_AUTH_aiCheckManage_Edit: 42,
  // 高峰预警-查看-delete
  old_AUTH_PeakWarning_View: 45,
  // 高峰预警-编辑-delete
  old_AUTH_PeakWarning_Edit: 46,
  old_AUTH_PeakWarning_Export: 46,
  // 小哥上报平台-delete
  old_AUTH_courierReport_View: 47,
  old_AUTH_courierReport_Export: 47,

  // 未知权限-delete
  old_AUTH_SortingManage_SearchAndEdit: 18,
  old_AUTH_SortingManage_EditBatch: 19,

  // 数据运营-其他数据导出-埋点数据-查看
  old_AUTH_TrackData_View: 53,
  old_AUTH_regionTaskLabel_View: 56,
  old_AUTH_RegionTaskLabel_Export: 57,
};

console.log('authMap.length is >>>>>>>>>>>', Object.keys(authMap).length);